### ISSUE TITLE
Possibly wrong mutation in documentation example #.addEdgeWithKey

### ISSUE THREAD

**Issue by chbert** [graphology/documentation#17]
https://github.com/graphology/documentation/blob/83cafe21bdf4a4481a910f245518335db2abd694/docs/mutation.md#addedgewithkey

Example uses "const edge = graph.**addEdge**('John->Jack', 'John', 'Jack');" instead of **.addEdgeWithKey**?

PS: Completely new to graphology 😄

**Comment by Yomguithereal** [comment]
Indeed the example was erroneous. Thanks for noticing @chbert, this should be fixed now :)
